<?xml version="1.0" encoding="UTF-8"?><testrun name="TestDealCardMove" project="jherreroestrada_MountOlympus" tests="4" started="4" failures="1" errors="0" ignored="0">
  <testsuite name="jherreroestrada.TestDealCardMove" time="2.269">
    <testcase name="testTableauToFoundationMove2" classname="jherreroestrada.TestDealCardMove" time="1.292"/>
    <testcase name="testDealCardMove" classname="jherreroestrada.TestDealCardMove" time="0.324"/>
    <testcase name="testTableauToTableauMove" classname="jherreroestrada.TestDealCardMove" time="0.333"/>
    <testcase name="testTableauToFoundationMove" classname="jherreroestrada.TestDealCardMove" time="0.32">
      <failure>junit.framework.AssertionFailedError: expected:&lt;0&gt; but was:&lt;2&gt;
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at junit.framework.Assert.assertEquals(Assert.java:241)
	at junit.framework.TestCase.assertEquals(TestCase.java:409)
	at jherreroestrada.TestDealCardMove.testTableauToFoundationMove(TestDealCardMove.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:121)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

</failure>
    </testcase>
  </testsuite>
</testrun>
